### ISSUE TITLE
Cannot remove splitter from empty shape

### ISSUE THREAD

**Issue by foertel** [execuc/LCInterlocking#29]
>Running the Python command 'export_command' failed:
>Traceback (most recent call last):
>  File "/home/felix/snap/freecad/8/.FreeCAD/Mod/LCInterlocking/ExportPanel.py", line 78, in Activated
>    self.export_list(parts_list, new_doc)
>  File "/home/felix/snap/freecad/8/.FreeCAD/Mod/LCInterlocking/ExportPanel.py", line 94, in export_list
>    transform_shape(part, new_part, freecad_document)
>  File "/home/felix/snap/freecad/8/.FreeCAD/Mod/LCInterlocking/ExportPanel.py", line 49, in transform_shape
>    new_part_feature.Shape = part_feature.Shape.removeSplitter()
>
>Cannot remove splitter from empty shape

FreeCAD 0.18 (16093) with LCInterlocking from the addon manager.

It happens, when I try to export all objects. If I just choose the active Bodies, it works okay. As soon as your drawing gets a little more complex (like a lot of cutouts and stuff), it's hard to export all the right objects. Maybe we can add a filter to ignore empty shapes?

**Comment by luzpaz** [comment]
@foertel can you test with FreeCAD v0.19 and report ?

**Comment by luzpaz** [comment]
@foertel please follow-up

**Comment by undercoverdesigns** [comment]
I can verify that this happens in 0.19, as well.  If I select the Multijoin, I get this error.  If I select the individual *_tab objects, export works fine.
