### ISSUE TITLE
Unable to get CrossPiece to work

### ISSUE THREAD

**Issue by rebeltaz** [execuc/LCInterlocking#60]
I am trying to learn how to use this plugin on this test project (in FreeCAD v0.19 under Ubuntu 18.04 LTS). When I add both pieces to the CrossPiece dialog and run Preview, it tells me this:

```
00:20:26  Traceback (most recent call last):
  File "/home/derek/.FreeCAD/Mod/LCInterlocking/panel/crosspiece.py", line 56, in onChanged
    self.preview(fp)
  File "/home/derek/.FreeCAD/Mod/LCInterlocking/panel/crosspiece.py", line 100, in preview
    computed_parts = make_cross_parts(parts)
  File "/home/derek/.FreeCAD/Mod/LCInterlocking/lasercut/crosspart.py", line 372, in make_cross_parts
    raise ValueError("Not managed")
<class 'ValueError'>: Not managed

```

I tried making "Simple Copies" of both pad operations and working with those instead, but I get the same error. I even tried creating the pieces as Parts directly using Cubes and I still get the same error.

Am I doing something wrong?
[test.FCStd.zip](https://github.com/execuc/LCInterlocking/files/9532575/test.FCStd.zip)

**Comment by Guertelwal** [comment]
I have the same Problem with FreeCAD 0.20.1

**Comment by reox** [comment]
I get a different error here:
```
19:44:21  Traceback (most recent call last):
  File "FreeCAD\Mod\LCInterlocking\panel\crosspiece.py", line 54, in onChanged
    self.execute(fp)
  File "FreeCAD\Mod\LCInterlocking\panel\crosspiece.py", line 136, in execute
    computed_parts = make_cross_parts(parts)
  File "FreeCAD\Mod\LCInterlocking\lasercut\crosspart.py", line 345, in make_cross_parts
    second_face = referential_faces[1]
<class 'IndexError'>: list index out of range
```

However, I think I have found some hints why it fails in certain cases: It only fails for me, when one of the surfaces at the cross-piece intersect each other. That might be the case when two sloped surfaces are used:
![image](https://user-images.githubusercontent.com/431045/231541797-87f9170d-f5c7-44d1-b895-f86cb79a8c33.png)

If instead two planar surfaces are used, the cross-piece works perfectly:
![image](https://user-images.githubusercontent.com/431045/231542037-d4048730-0bb5-424f-9169-561b2f965259.png)
